### ISSUE TITLE
smartblog categories rss does not respect SSL

### ISSUE THREAD

**Issue by cd2500** [smartdatasoft/smartblog#100]
On shops with SSL-certificate you will have insecure load on rss.php of smartblogcategories module.

**Comment by photinia73** [comment]
Hello!
Can you help me? PS 1.7.5. with ssl
I can`t apply any hook to rss, there is a lot of errors.
![image](https://user-images.githubusercontent.com/50954519/59274751-a6d2e200-8c63-11e9-9bf3-e8767d25699c.png)

**Comment by photinia73** [comment]
I am not sure I need to apply the hook, may be RSS works in the background mode... Sorry ,but not know a lot of RSS....

**Comment by Enumbin** [comment]
Can you please explain some more about what you want?
Please open support ticket on https://support.classydevs.com/support/
