### ISSUE TITLE
Missing getTranslator() function on the module

### ISSUE THREAD

**Issue by josenjo** [smartdatasoft/smartblog#101]
On AdminBlogPostController.php:

Fatal error: Call to undefined method Context::getTranslator() in ....\modules\smartblog\controllers\admin\AdminBlogPostController.php on line 91

On AdminBlogCategoryController.php:

Fatal error: Call to undefined method Context::getTranslator() in ....\modules\smartblog\controllers\admin\AdminBlogCategoryController.php on line 101

These errors shown on smartblog v3.0.0

**Comment by smartdatasoft** [comment]
which prestashop version you have install the module

**Comment by rjnaghera** [comment]
1.6.1.23

**Comment by winniezz** [comment]
same here with 1.6.1.24 and plugin v3

**Comment by Enumbin** [comment]
Our main development branch is for 1.7.x and Other branch 1.6.1.x for PrestaShop 1.6.1.x version.

After a long time we SmartDataSoft is back to dedicated PrestaShop development as ClassyDevs.

For further support open support ticket at https://support.classydevs.com/support/
