### ISSUE TITLE
Problem with url rewriting in htaccess for images/links in blog post

### ISSUE THREAD

**Issue by 4zur3** [smartdatasoft/smartblog#104]
I have a problem with the loading of images inside the blog post, I can see that the module add in the .htaccess theses lines : 

#Images Blog
RewriteRule ^blog/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}modules/smartblog/images/$1$2$3.jpg [L]
RewriteRule ^blog/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}modules/smartblog/images/$1$2.jpg [L]

The rewrite rules is working when my domain name is without any dashes for examples :

https://exampletest.com/blog/image-format.jpg 👍 

but NOT working when like this : 
https://example-test.com/blog/image-format.jpg  👎 

because there is a dash in the domaine name, do you know any workaround or am I missing something about the rewrite rules ? Is there any fixes ? Is anyone got this problem before ? 

Best regards,

**Comment by smartdatasoft** [comment]
Hello, 4zur3 
You can open a ticket in our support system https://prestasian.com/support with your site information. Our technical expert will help you.

Thank you
