### ISSUE TITLE
Error 503: Service unavailable

### ISSUE THREAD

**Issue by Rafa410** [smartdatasoft/smartblog#105]
After installing the last version of this module (smartblog-v3.0.0) in Prestashop 1.7.4.4 the whole website stopped working. When I try to access the website, it keeps loading for 1-2 minutes and then I get the Error 503 (Service unavailable)

![service_unavailable](https://user-images.githubusercontent.com/45756370/49726590-a898fa00-fc6e-11e8-8e6e-cff7c7b768f0.jpg)

Any idea on how to fix this?

**Comment by smartdatasoft** [comment]
Please use our latest version from development branch
