### ISSUE TITLE
Error in AdminBlogPostController.php (line 638) - curly brackets are missing?

### ISSUE THREAD

**Issue by maba-designer** [smartdatasoft/smartblog#106]
Hi, 
I have installed manually Smartblog V3.0.0.0 in prestashop v1.7.4.2. the blog section works correctly. There are the default posts, the categories etc .. The problem is in the back-end because when I create a post it returns me "500 Internal Server Error". 
In debug mode it indicates me the error in:
..modules/smartblog/controllers/admin/AdminBlogPostController.php (line 638)

I checked this file and I notice curly brackets are missing in many loops (IF)

Can the bug problem be this? Thank you

![cattura](https://user-images.githubusercontent.com/45849133/49939283-b3f15d00-fedc-11e8-90d3-95dfd4186be5.PNG)
![cattura2](https://user-images.githubusercontent.com/45849133/49939396-0894d800-fedd-11e8-988a-4ca869337633.PNG)

**Comment by Rafa410** [comment]
I don't think this is the problem, you can omit curly brackets if there is a single line inside the if statement

**Comment by maba-designer** [comment]
ok, thanks for your feedback. How to solve this? 
Unfortunately I'm not a developer and I did not know this detail.

**Comment by fromcouch** [comment]
I know if a lot of time. But I had same problem.

Go to 
_..modules/smartblog/controllers/admin/AdminBlogPostController.php_ 

And near line 119 add **$isNewTheme** to declaration and to **parent::setMedia()**
```
public function setMedia($isNewTheme = false) {
        parent::setMedia($isNewTheme);
        $this->addJqueryPlugin(array('tagify', 'tablednd', 'autocomplete'));
}
```
