### ISSUE TITLE
No Captcha image generated

### ISSUE THREAD

**Issue by pantagru** [smartdatasoft/smartblog#113]
Captcha image doesn't work, it'is not generated. Any ideas?
![screenshot_2019-01-17 prova2](https://user-images.githubusercontent.com/41157394/51315950-ae46e400-1a53-11e9-9c83-6408a0a72692.png)

**Comment by pantagru** [comment]
And also without catcha, the comment is not sent. Any solutions?

**Comment by smartdatasoft** [comment]
Please open ticket in our support system https://support.classydevs.com for any issue. it is working fine in our development branch.
