### ISSUE TITLE
SmartBlog v2.2.0 - Prestashop 1.6 - Title & Meta-data problem

### ISSUE THREAD

**Issue by szrono** [smartdatasoft/smartblog#115]
Hello,

I have a problem with the Smartblog module installed in my store.
Unfortunately, the title is not displayed in the posts you have added. It appears only on the list of articles, but after switching to a specific article disappears (attachment 1).
The second problem - Although Meta descriptions are not shown, they are not visible (attachment 2)

![1](https://user-images.githubusercontent.com/46955510/51591727-15e6ae80-1eee-11e9-9a50-c63cdea08a9b.png)
![2](https://user-images.githubusercontent.com/46955510/51591728-15e6ae80-1eee-11e9-8e23-3ba7e22264fd.png)

Please help solve this two problems.

Best regards,
Kamil

**Comment by szrono** [comment]
Does anyone have any knowledge how to solve these two problems?

**Comment by luisjsolsona** [comment]
No body? no solution to this??

**Comment by CreateYourOwnMobileApp** [comment]
You have to upload your content which is very necessary for the site also title and keyword but, all the content must be unique. [Build An App   Like Snapchat](https://developapplike.com/snapchat/)
