### ISSUE TITLE
 problem with creating a url with tags in smartblog

### ISSUE THREAD

**Issue by MrBartek007** [smartdatasoft/smartblog#116]
When we have a tag composed of two words "home book" - url does not work.

http: //localhost/smartblog/tag/home%20book.html - error 404 is created

When we have one word in the tag, e.g. "home" everything works correctly:
http://localhost/smartblog/tag/home.html

How should I unhook this problem?

**Comment by goldsteinrazvan** [comment]
I had the same problem, which I solved by modifying SmartBlogLink.php at line 314: 
Find ` $params['tag'] = $tagName;`  and change it to ` $params['tag'] = urlencode($tagName);`
Hope it helps!

**Comment by barapuha** [comment]
I have the same problem, tell me where is this file  SmartBlogLink.php ?

I can not find him

**Comment by jonnydhaka** [comment]
please download latest version, we fix this problem, if face any issue in future please contact our support athttps://support.classydevs.com/
