### ISSUE TITLE
Unknown column 'cl.name' in 'field list'

### ISSUE THREAD

**Issue by feyll** [smartdatasoft/smartblog#118]
hi, can someone please suggest me how to correct this error?
![Screenshot (78)](https://user-images.githubusercontent.com/27018255/54355998-d0776f80-465a-11e9-82f5-d3b09d9425d4.png)

**Comment by feyll** [comment]
?

**Comment by fromcouch** [comment]
I had the same problem upgrading smartblog because don't have upgrade sql system. You need to create manually.

**Comment by jae1911** [comment]
Greetings.
Is there a way to do a database upgrade without having to either re-install the module or create the fields by hand?

**Comment by jonnydhaka** [comment]
if face any issue then please contact with our support at https://support.classydevs.com/

**Comment by jae1911** [comment]
> if face any issue then please contact with our support at https://support.classydevs.com/

I mean a real solution, not some kind of shitty paid support.

**Comment by fromcouch** [comment]
@Jaedotmoe i don't remember well. But you need to go to database and update tables manually.
You have code here: 
https://github.com/smartdatasoft/smartblog/blob/develop/sql/install.php

you need to review table by table and compare with schema. Problem is that upgrade not really touch database. Only if you install/uninstall. But if you uninstall code DELETE all module tables. Then isn't a solution.

Good point will be developer write code for correct upgrading. But meanwhile you need to review database tables manually.

**Comment by jae1911** [comment]
@fromcouch yes, I did that previously but it's not really usable for people that don't know how to use PHPMyAdmin or PSQL.

I'm gonna make end up forking this plugin to make it usable.
