### ISSUE TITLE
Cannot insta on Presta 1.7.5

### ISSUE THREAD

**Issue by thierry-laval** [smartdatasoft/smartblog#120]
Where can i test a new version ? Thank a lot...

**Comment by thierry-laval** [comment]
i try v3 but make a lot errors in debug mod... Pleaseeeee :-) do you have a new version? Your module are so beauty

**Comment by thierry-laval** [comment]
Apparently the problem comes from php version 7.2.
The blog module only works up to 7.1 PHP
Who could change that?
Thank you

**Comment by thierry-laval** [comment]
NO ?? Nobody interest for this module ?

**Comment by Enumbin** [comment]
Hello Brother, 

We are back. We are updating this module to be the best blog module for PrestaShop. We have opened a new team named [ClassyDevs](https://classydevs.com/) with some very experienced developers.

You can check our new best modules at [ClassyDevs](https://classydevs.com/)

We have a module to add extra tabs to the products of your PrestaShop site.

**Comment by Enumbin** [comment]
Open support ticket on support.classydevs.com
