### ISSUE TITLE
Smartblog Category ,post,image page error

### ISSUE THREAD

**Issue by rjnaghera** [smartdatasoft/smartblog#121]
| <br />
-- | --
  | <b>Fatal error</b>:  Uncaught Error: Call to undefined method Context::getTranslator() in C:\xampp\htdocs\prestashop16\modules\smartblog\controllers\admin\AdminBlogCategoryController.php:101
  | Stack trace:
  | #0 C:\xampp\htdocs\prestashop16\modules\smartblog\controllers\admin\AdminBlogCategoryController.php(34): AdminBlogCategoryController-&gt;l('Delete selected')
  | #1 C:\xampp\htdocs\prestashop16\classes\controller\Controller.php(134): AdminBlogCategoryController-&gt;__construct(false, false)
  | #2 C:\xampp\htdocs\prestashop16\classes\Dispatcher.php(359): ControllerCore::getController('AdminBlogCatego...')
  | #3 C:\xampp\htdocs\prestashop16\admin241dbfihr\index.php(58): DispatcherCore-&gt;dispatch()
  | #4 {main}
  | thrown in <b>C:\xampp\htdocs\prestashop16\modules\smartblog\controllers\admin\AdminBlogCategoryController.php</b> on line <b>101</b><br />
  |

**Comment by rjnaghera** [comment]
in prestashop version 1.6.1.23

**Comment by jonnydhaka** [comment]
please update prestashop version 1.7 then face any issue please contact our support at https://support.classydevs.com/
