### ISSUE TITLE
Main blog url not changing

### ISSUE THREAD

**Issue by Gazi96** [smartdatasoft/smartblog#129]
Hi, I try to change url 
from https://mydomain.com/smartblog.html 
to https://mydomain.com/smartblog.html
, but nothing change in admin panel and url is still https://mydomain.com/smartblog.html 

The problem is on prestashop 1.7.

**Comment by jonnydhaka** [comment]
https://github.com/smartdatasoft/smartblog/pull/145 

please update latest version, then check
