### ISSUE TITLE
meta descrption does not display

### ISSUE THREAD

**Issue by xiaoyuan1998** [smartdatasoft/smartblog#130]
Hello Admin,

I configured the meta description, but it does not display,  it is important for our seo

myprestashop version is 1.7.4

![image](https://user-images.githubusercontent.com/7703076/65880686-763dc200-e392-11e9-8e17-675683c5e7bf.png)

BLOG LINK: https://maison-des-meches.fr/blogs/5_tissage-naturel-longueur-nombre-paquets.html

**Comment by KIBstore** [comment]
I have the same problem. How to solve it?
myprestashop version is 1.7.6.1
Link - https://kibstore.com/ru/kibstoreblog/21_byudzhetnoe-reshenie-ot-lidera-rynka-videonab

**Comment by Enumbin** [comment]
We have fixed the issue in version 4.0.0. For further issues create support ticket at https://support.classydevs.com/support/
