### ISSUE TITLE
Blog articles are not displayed

### ISSUE THREAD

**Issue by christianchf** [smartdatasoft/smartblog#134]
I have the Smartblog module and the Pretty urls module installed in a Prestashop 1.7, and I have the following problem:

The page of the list of all the blog entries looks correctly but the blog articles are not seen, when you want to enter an article, the url is redirected to an error 404. Is it possible that there is any incompatibility between the two modules ? If so, there is some way to fix it.

A greeting and thanks in advance.

**Comment by jonnydhaka** [comment]
please download latest version, if not solved then contact with our support https://support.classydevs.com/
