### ISSUE TITLE
redirect from back office

### ISSUE THREAD

**Issue by nathanl361** [smartdatasoft/smartblog#135]
Hi all,

When I want to go to back office to creat a new post, here is what happen :

I click on the blog tab  -> blog post

2 sec after it redirect to this url : mywebsite.com/.well-known/captcha/

same with blog comment and other tab.
front office works fine
Yesterday it was working fine.

Thanks :)

**Comment by nicohery** [comment]
It's about Smartblog Promotion script. I patched it in modules/smartblog/smartblog.php 
Find getSmartPromotion method and return null. 

```
getSmartPromotion(){
            return "";
            /* ... */
}
```

**Comment by jonnydhaka** [comment]
issue fix, we remove code and return "".
Thank you
