### ISSUE TITLE
php fatal error

### ISSUE THREAD

**Issue by smithikakart** [smartdatasoft/smartblog#137]
Prestashop V-1.7.6.4 smart blog V-2.0.1
PHP Fatal error:  Uncaught  --> Smarty: Template './category_loop.tpl' cannot be relative to template of resource type 'module' <-- 
  thrown in /home/smithikakart/public_html/vendor/smarty/smarty/libs/sysplugins/smarty_internal_resource_file.php on line 116

**Comment by smithikakart** [comment]
Any solution?

**Comment by jonnydhaka** [comment]
please update to latest version. its 3.0.0
"https://support.classydevs.com/" 
Thank you
