### ISSUE TITLE
Category-top-menu appears on smartblog.html

### ISSUE THREAD

**Issue by KoveZoli** [smartdatasoft/smartblog#138]
Hi,

The product category-top-menu appears on /smartblog.html, although it shouldn't be there.
I disabled the "category tree" and "layered search" on the positions page (module-smartblog-search / category / tagpost / details / archive), but I don't see just the module-smartblog file.
What could be the solution?
Thank you!
PS1.7
![feleselges_1](https://user-images.githubusercontent.com/52235230/91553413-a472ab80-e92d-11ea-83a2-5d794fa06170.jpg)
![feleselges_4](https://user-images.githubusercontent.com/52235230/91553427-ac325000-e92d-11ea-8b56-51220d9928f6.jpg)
![feleselges_3](https://user-images.githubusercontent.com/52235230/91553430-accae680-e92d-11ea-9493-4b8984a5fd8d.jpg)
![feleselges_2](https://user-images.githubusercontent.com/52235230/91553431-accae680-e92d-11ea-9190-edda7a179f6f.jpg)

**Comment by jonnydhaka** [comment]
Try to contact with our support team "https://support.classydevs.com/"
