### ISSUE TITLE
404 if post no present, 301 not redirected to the canonical url

### ISSUE THREAD

**Issue by vladdnepr** [smartdatasoft/smartblog#14]
Hi.

I just installed blog module on my shop, but if i fill in url unknown post url (example http://inome.com.ua/blog/123_test.html) - 404 not raised.

And if i change slug in url - i expect raised 301 to the original url, but displayed all the same article. its bad for SEO. Canonical page http://inome.com.ua/blog/5_manufacturers-shirts.html, url without 301 http://inome.com.ua/blog/5_manufacturers-shirts-wrong.html

**Comment by smartdatasoft** [comment]
Please update your blog with our new version
