### ISSUE TITLE
Images served over http

### ISSUE THREAD

**Issue by szykuc** [smartdatasoft/smartblog#140]
Hello,
i notice that images ares served over http but should over https.

I have ssl enebled everywhere.

When i echo $this->protocol_content in getImageLink() function in SmartBlogLink.php i get http://

**Comment by nosko-stojachkov** [comment]
I have the same problem.
Found a solution?

**Comment by SharakPL** [comment]
Duplicates #82, #85. You'll find answers there.

**Comment by jonnydhaka** [comment]
hi,
Thanks a lot . we will add this our next version.
If you have any problems in the future, you can contact our support.
https://support.classydevs.com/
Thank you
