### ISSUE TITLE
Featured images not saved ?

### ISSUE THREAD

**Issue by mranchon** [smartdatasoft/smartblog#141]
Hi,
I have Smartblog v3.0, but when I add a featured image, it is not saved in module/smartblog/images folder. However, I see the picture in the back office (posts list) but not in the front posts list, and I think it is saved in a temp folder.

When I do SQL query (SELECT) in the smart_blog_post table, "image" field is empty.

When I look in "element" tab on Chrome, the image path is the following: https://invinoveto.fr/blog/no-single-default/domaine-vessigaud.jpg instead of my featured image.

Someone have an idea please ? I'm using Prestashop 1.7.7, and I don't find any solution in issues section or stackoverflow.

Website: [https://invinoveto.fr/smartblog.html](url)

Thank you :)

**Comment by Pinnora** [comment]
I have this exact same issue - any help would be most welcome.

**Comment by mranchon** [comment]
@Pinnora After local test, on Prestashop 1.7.6, featured images appears..
In fact, the image path must contains post id. Like that: [https://invinoveto.fr/blog/**25-single-default**/domaine-vessigaud.jpg](url) instead of **no-single-default**. I don't know why, but it works with WAMP but not online..

**Comment by Pinnora** [comment]
Thanks. To be honest I ended up uninstalling the whole module and moved across to Xpert Blog instead, which works right from installation.

**Comment by mranchon** [comment]
After a day, I find a fix:
In category_loop.tpl: l.71
`src="http://invinoveto.fr/blog/{$post.id_post}-single-default/{$post.link_rewrite}.jpg"` instead of `src="{$smartbloglink->getImageLink($post.link_rewrite, $post.id_post, 'single-default')}"`

**Comment by jonnydhaka** [comment]
Hi,
test it from our end, its works perfectly. you can contact with our support.
https://support.classydevs.com/
Thank you
