### ISSUE TITLE
Can't change ' Main URL blog '

### ISSUE THREAD

**Issue by Bahwaimongars** [smartdatasoft/smartblog#142]
Hello,

I have an issue when im trying to change the main url blog, there is no effect.

Actually i have : 
www.mydomain.com/smartblog

i want to have : 

www.mydomain.com/blog (for example)

I suppose that, the main url blog change that, but there is no effect here.

anyone have a idea ?

**Comment by jonnydhaka** [comment]
Hi,
try to find your problem in my local, by don't found. when you use only "blog" Does it show any error ? check below screenshot. 
https://prnt.sc/xpb31d , https://prnt.sc/xpb41f 

Try to contact with our support team "https://support.classydevs.com/"
Thank you

**Comment by Bahwaimongars** [comment]
Hello,

When im trying to use blog or others names, no errors, no effect.
There is a screen of my conf blog page :

![image](https://user-images.githubusercontent.com/62238066/105985046-3fb5ab80-609b-11eb-851d-88971839d598.png)

We can see that, ' Main url Blog ' is set to patatis, and after save no changes :/

**Comment by jonnydhaka** [comment]
ok, Try to contact with our support team "https://support.classydevs.com/". they will fix this

**Comment by jonnydhaka** [comment]
https://github.com/smartdatasoft/smartblog/pull/145
please try to update latest version.
