### ISSUE TITLE
External links?

### ISSUE THREAD

**Issue by PrestaShark** [smartdatasoft/smartblog#15]
Hi,
I have found external links in posts.tpl file
Why they are there? Its not elegant even in free module
http://321cart.com/sellya/catalog/view/theme/default/image/loading.gif 

Also something like this
/wp/sellya/sellya/this-is-a-post-with-preview-image/#respond

**Comment by smartdatasoft** [comment]
Hello, that was a mistake i have found. we have remove all

**Comment by swasthya** [comment]
/wp/sellya/sellya/this-is-a-post-with-preview-image/#respond

still exists

**Comment by smartdatasoft** [comment]
Please use our latest versoin and then check.

**Comment by swasthya** [comment]
We downloaded it from the latest release https://github.com/smartdatasoft/smartblog/releases/tag/3.0.0  ;  3.0.0 ; e8181e3

We still find it @ line 168 in smartblog-v3.0.0(1)\smartblog\views\templates\front\posts.tpl

Let us know if we have not downloaded the latest. 

thanks 



![Screenshot(189)](https://user-images.githubusercontent.com/53976106/87486777-a8868a80-c659-11ea-8f59-c124eaf1b3cb.png)

**Comment by smartdatasoft** [comment]
hello, the id exits that is a bug but the issue with the external image which already removed.
thank you
