### ISSUE TITLE
module:smartblog/views/templates/front/posts.tp

### ISSUE THREAD

**Issue by Ledwis90** [smartdatasoft/smartblog#161]
Hello!

My head is about to blow up with the pligging.

First,,, I installed version 2.2 in a test enviroment, working perfect. I installed on my site, but did not display the content.

I installed version 3.0, and I am gerring Server error a 500 Server Error.

I activated debug  mode and:

![image](https://user-images.githubusercontent.com/78701836/107157162-e004ad80-6982-11eb-83b0-30884fbdd065.png)

[PrestaShopException]
Template 'module:smartblog/views/templates/front/posts.tpl' not found
at line 66 in file classes/controller/ModuleFrontController.php

What I am doing wrong?

Very thanks for assistance,

**Comment by Archeter** [comment]
The same... did not display the content (full post). How to fix it?
PS 1.7.7.1
PHP: 7.2.34

**Comment by jonnydhaka** [comment]
please download latest version and then try again. Also, you can contact our support at https://support.classydevs.com/
Thank you
