### ISSUE TITLE
images not showing in Prestashop 1.7.7.5

### ISSUE THREAD

**Issue by etsmes** [smartdatasoft/smartblog#198]
Hi,

I have updated my Prestashop to version 1.7.7.5 and the Post images have stopped showing.
They are also not displayed in the SmartBlog Home Latest News module.

Thank you,

Josep

**Comment by smartdatasoft** [comment]
Please open ticket in https://support.classydevs.com
Thank you

**Comment by Enumbin** [comment]
Supported
