### ISSUE TITLE
Usage of $content as smarty variable

### ISSUE THREAD

**Issue by lu-w** [smartdatasoft/smartblog#20]
Hey,

the `$content` variable which is set in `controllers/front/details.php` on line 47 conflicts with smarty variables set by other modules:

``` php
 'content'=>$post['content'],
```

Consider re-evaluating your naming scheme. I propose a scheme such as `$smartblog_content`. This will make the global smartblog variables unique.

The current approach results in a conflict with the `$content` variable set by the contentBox module, resulting in a bug where the content of the blog posts are not displayed.

As a hotfix, I just renamed the smarty variable to

``` php
 'content_hopefullyunique'=>$post['content'],
```

and edited the appropriate tpl file `views/templates/front/posts.tpl`:

``` html
<div class="sdsarticle-des">
    {$content_hopefullyunique}
</div>
```

And everything works just fine.

**Comment by JKE-be** [comment]
:+1:

**Comment by abasweb** [comment]
Hi,

I applied this fix in smartblog 2.0.2 an don't view any change.... :(. I need help.

**Comment by smartdatasoft** [comment]
We have change this can you check our new version.

**Comment by RalphW78** [comment]
Hi there, 

I have some issues with using SmartBlog v2.2 with Presta 1.6.1.18. It looks like it was installed correctly, but for some reasons, it does not display the full posts. When you click on the post, it shows only short version (title, short description and picture) + comments under it. There are no options to open the post deeper to see the actual body of the post. 
Any suggestions why this is the case? Thank you in advance
![smartblog post issue](https://user-images.githubusercontent.com/47652844/52834483-29c0b180-3136-11e9-90fe-bc494e54a7f7.jpg)
