### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by ivopisarovic** [smartdatasoft/smartblog#23]
In comments translations defined like 
<code>{l s="Reply" mod="smartblog"}</code>
phrases are not recognized in the back office translations. 
Replacing quotation marks with apostrophs solves the problem.
<code>{l s='Reply' mod='smartblog'}</code>
Prestashop 1.6.0.14

**Comment by ivopisarovic** [comment]
Sorry, already repaired.

**Comment by ivopisarovic** [comment]
Another problems: Admin type image editing and comment form errors handling via AJAX are always in English. Phrases appears in admin translation tool, but aren't never used.

**Comment by ivopisarovic** [comment]
I have made a pull request with repairs for these errors, please check.

**Comment by smartdatasoft** [comment]
This issue was fixed , you can check our new version
