### ISSUE TITLE
Link post image to post

### ISSUE THREAD

**Issue by megamurmulis** [smartdatasoft/smartblog#27]
### Request: Link post image to post in category listing:

<b>FILE:</b>  smartblog/views/templates/front/category_loop.tpl
Change from:

```
    <div class="articleContent">
        <a itemprop="url" title="{$post.meta_title}" class="imageFeaturedLink">
```

To:

```
    <div class="articleContent">
:        <a itemprop="url" title="{$post.meta_title}" class="imageFeaturedLink" href="{smartblog::GetSmartBlogLink('smartblog_post',$options)}">
```

**Comment by smartdatasoft** [comment]
We have apply new image call rules, you can use that   <img itemprop="image" alt="{$post.meta_title|escape:'htmlall':'UTF-8'}" src="{$smartbloglink->getImageLink($post.link_rewrite, $post.id_post, 'single-default')}" class="imageFeatured">
