### ISSUE TITLE
Use single post meta description / keywords when set

### ISSUE THREAD

**Issue by megamurmulis** [smartdatasoft/smartblog#28]
<b>To avoid confusion - updated this to match latest revision:</b>

#### Issue: Currently single post page always uses global meta description / keywords values, even when post actually has data.
Single post does not set it's meta data => add code to override global value with post's meta data (if set):

<b>a) Handle in main controller:</b> - uncomment code:
<b>FILE: </b> smartblog/classes/controllers/FrontController.php
```
-       /*
	if ( Tools::getvalue('id_category') && Tools::getvalue('id_category') != Null) {
		$this->context->smarty->assign(BlogCategory::GetMetaByCategory(Tools::getvalue('id_category')));
	}
	if (Tools::getvalue('id_post') && Tools::getvalue('id_post') != Null) {
		$this->context->smarty->assign(SmartBlogPost::GetPostMetaByPost(Tools::getvalue('id_post')));
	}
	if (Tools::getvalue('id_category') == Null && Tools::getvalue('id_post') == Null) {
		$meta['meta_title'] = Configuration::get('smartblogmetatitle');
		$meta['meta_description'] = Configuration::get('smartblogmetadescrip');
		$meta['meta_keywords'] = Configuration::get('smartblogmetakeyword');
		$this->context->smarty->assign($meta);
	}
-	*/
```

<b>b) Handle in post controller</b>
<b>FILE:</b>  smartblog/controllers/front/details.php
```
    public function initContent()
        ...
        $this->context->smarty->assign(array(
            ...
        ));
+    $this->context->smarty->assign( SmartBlogPost::GetPostMetaByPost( $id_post ) );
```
<b>FILE:</b>  smartblog/controllers/front/category.php
```
    public function initContent()
        ...
        $this->context->smarty->assign(array(
            ...
        ));
+    $this->context->smarty->assign( BlogCategory::GetMetaByCategory( $id_category ) );
```

**Comment by catbirdbingo** [comment]
i have the same issue, this is the only solve but it didnt work for me :( presta 1.6

**Comment by InterLaw-PL** [comment]
Yes, it didn't work :(
Presta: 1.6

On smartblog/controllers/front/details.php file doesn't have your code @megamurmulis 
Do you have any ideas? :(

**Comment by megamurmulis** [comment]
That's because you were supposed to add that code to details.php <b>OR fix `#1`</b>..

- i edited my post and changed some wording to make it more clear..

(From what i can see - `#2` might not even be necessary if `#1` is fixed - as `initContent()` in `details.php` is already calling `parent::initContent();` (so `GetPostMetaByPost()` should set that via `smartblogModuleFrontController` => so problem is due boolean eval issue in `getpost()`)

**Comment by InterLaw-PL** [comment]
It works! You are genius @megamurmulis ! 👍 
Can you solve the problem with title, meta description in SmartBlog category?
Because it is the same problem. Thank you for everything!

**Comment by megamurmulis** [comment]
First - note that there are multiple revisions floating around - some have some code disabled in `FrontController.php`, some having it, but issues in other places - my old code was based on older revision....
- i now checked out latest revision - in it i see that `FrontController.php` isn't setting (commented out).

So if you are using latest version you should:
a) restore code in `FrontController.php`.
b) manually set it in the post/category controller (`details.php`, `category.php`)...


If you want to set values manually in controller:
1. `details.php` -  as noted could have replace that code with one call to:
```
  $this->context->smarty->assign( SmartBlogPost::GetPostMetaByPost( $id_post ) );
```

2. For `category.php`:
```
  $this->context->smarty->assign( BlogCategory::GetMetaByCategory( $id_category ) );
```

---
~ As to that PHP eval issue - i tried my old test/debug script in few hostings and works fine, so no idea what PHP version / config was the cause.. (both of these two should be the same).
```
  if ( !$variabe = .... )
  if ( ! ($variabe = ....) )
```
So unless you hosting is really old - should not have any problems with this....

**Comment by smartdatasoft** [comment]
Hello, we have fix this, can any one check

**Comment by wordliner** [comment]
Looks like the problem is still there, for me. No meta data.

**Comment by jflaque** [comment]
Hello, I have version 2.0.1. And I can not show the title, description and keywords.
How can I solve it? Thanks.

**Comment by szrono** [comment]
> 
> 
> To avoid confusion - updated this to match latest revision:
> #### Issue: Currently single post page always uses global meta description / keywords values, even when post actually has data.
> 
> Single post does not set it's meta data => add code to override global value with post's meta data (if set):
> 
> a) Handle in main controller: - uncomment code:
> FILE: smartblog/classes/controllers/FrontController.php
> 
> ```
> -       /*
> 	if ( Tools::getvalue('id_category') && Tools::getvalue('id_category') != Null) {
> 		$this->context->smarty->assign(BlogCategory::GetMetaByCategory(Tools::getvalue('id_category')));
> 	}
> 	if (Tools::getvalue('id_post') && Tools::getvalue('id_post') != Null) {
> 		$this->context->smarty->assign(SmartBlogPost::GetPostMetaByPost(Tools::getvalue('id_post')));
> 	}
> 	if (Tools::getvalue('id_category') == Null && Tools::getvalue('id_post') == Null) {
> 		$meta['meta_title'] = Configuration::get('smartblogmetatitle');
> 		$meta['meta_description'] = Configuration::get('smartblogmetadescrip');
> 		$meta['meta_keywords'] = Configuration::get('smartblogmetakeyword');
> 		$this->context->smarty->assign($meta);
> 	}
> -	*/
> ```
> 
> b) Handle in post controller
> FILE: smartblog/controllers/front/details.php
> 
> ```
>     public function initContent()
>         ...
>         $this->context->smarty->assign(array(
>             ...
>         ));
> +    $this->context->smarty->assign( SmartBlogPost::GetPostMetaByPost( $id_post ) );
> ```
> 
> FILE: smartblog/controllers/front/category.php
> 
> ```
>     public function initContent()
>         ...
>         $this->context->smarty->assign(array(
>             ...
>         ));
> +    $this->context->smarty->assign( BlogCategory::GetMetaByCategory( $id_category ) );
> ```

Hello,

I had a problem with the meta-descriptions on the blog. I followed the above guidelines, which helped in this matter, but there was a problem with the main page of the blog - After going to the "Blog" tab on my site (https://www.allerolladen.de/blog) "Blank page" is displayed . Post pages work normally...

**Comment by megamurmulis** [comment]
`Blank page = Fatal Error (but display_errors is false, so does not show anything - you can try setting debug mode on to see error (in `config/defines.inc.php` ):  `define('_PS_MODE_DEV_', true);`

Also - make sure you did not leave those +/- at the start of lines (those were just marks, which lines added/changed).

**Comment by megamurmulis** [comment]
Blank page = PHP fatal error (but when `display_errors=Off` - does not show anything.
You can try setting debug mode in PS to see errors:
    config/defines.inc.php
    define('PS_MODE_DEV', true);

Also - make sure you did not leave those +/- at the start of lines (those were just marks, which lines added/changed)...

**Comment by szrono** [comment]
> Blank page = PHP fatal error (but when `display_errors=Off` - does not show anything.
> You can try setting debug mode in PS to see errors:
> config/defines.inc.php
> define('PS_MODE_DEV', true);
> 
> Also - make sure you did not leave those +/- at the start of lines (those were just marks, which lines added/changed)...

Thanks for the answer. Display errors is active, but "Blank page" still appears - it does not show any error...

I'm not sure whether I have modified the contents of the Category and Details files properly, I add them in the attachment - could I ask you to check their correctness?

[category.txt](https://github.com/smartdatasoft/smartblog/files/2857206/category.txt)
[details.txt](https://github.com/smartdatasoft/smartblog/files/2857207/details.txt)

Thanks and best regards,
Kamil

**Comment by megamurmulis** [comment]
That static function has been removed - should work without this anyway, so remove line from category.txt:
```
$this->context->smarty->assign( BlogCategory::GetMetaByCategory( $id_category ) );
```

**Comment by szrono** [comment]
> 
> 
> That static function has been removed - should work without this anyway, so remove line from category.txt:
> 
> ```
> $this->context->smarty->assign( BlogCategory::GetMetaByCategory( $id_category ) );
> ```

It works! Thank You so much! :+1:

**Comment by Enumbin** [comment]
We have fixed the issue in version 4. if any issue please open ticket in [support.classydevs.com](https://support.classydevs.com/support/)
