### ISSUE TITLE
Problem with URL Rewrite for categories and posts

### ISSUE THREAD

**Issue by afabri73** [smartdatasoft/smartblog#32]
Hi,
I'm a web developer and I use your module in a prestashop website.
I have some problems with the url rewrite.
I would to remove the {id} before the slug in the url of all blog pages.
I configured the blog base url as: /blog/posts
The actual url for categories is: /blog/posts/category/3-events
The actual url for posts is: /blog/posts/8-test

For test, we tried to change "_" with "-" in your "/modules/smartblog/smartblog.php" file, but the urls are the same.

The friendly url must be:
- Blog: **/blog/posts**
- Categories: **/blog/posts/events**
- Posts: **/blog/posts/events/test**

How can I do to solve the problem?
Thank you and I look forward to your reply.
Adriano

**Comment by SharakPL** [comment]
First I'd suggest disabling cache and forcing file compile in preferences. Then go to Preferences -> SEO & URL and save htaccess configuration again (doesn't matter you didn't change anything). Helped with images' url rewriting. Maybe will help on this too...

**Comment by Enumbin** [comment]
I checked the issue. As @SharakPL  said, refreshing the urls in SEO & URL will fix the issue.
