### ISSUE TITLE
Error on new blog category save

### ISSUE THREAD

**Issue by sum1190** [smartdatasoft/smartblog#33]
Hi,
When I try to save a new Blog category in Prestashop 1.6, the module return this error:

`smart_blog_category (Unknown column 'name' in 'field list')`

I've tried to look at the DB and as I can see, there's no 'name' column on smart_blog_category. 
How can I fix this?
## 

Edit 22/07 23.39

I've noticed that in the table `smart_blog_category_lang` the column `name` is missed. Could it be an error on module setup file?
I've added it manually but I'm getting some other sparse error..

**Comment by smartdatasoft** [comment]
no this must not error. did you install correctly

**Comment by smartdatasoft** [comment]
Please check our new version
