### ISSUE TITLE
About url rewriting problems

### ISSUE THREAD

**Issue by skobeo** [smartdatasoft/smartblog#36]
Hi, trying to deal with the last version, 2.1.4, everything seems to be ok except url for single post. 
when i try 
http://www.xxxxxxxx.com/blog/new-post

i've got an error message on white screen with 

This page has moved
Please use the following URL instead: http://www.xxxxxxxx.com/blog/?slug=new-post&module=smartblog

Edit. cache empty, .htaccess generate from back office...

thanks for issue

**Comment by smartdatasoft** [comment]
hello, are you installa freshly or update the old version

**Comment by dmaglio** [comment]
same issue

**Comment by smartdatasoft** [comment]
Our url rewrite system is optimized and changed, please check now
