### ISSUE TITLE
Featured images

### ISSUE THREAD

**Issue by Q-Silve** [smartdatasoft/smartblog#37]
Hi

The 'featured images' are not showing on the front office.
Any idea of where it could come from?

Thanks,
QS.

**Comment by selwynorren** [comment]
Hi,

Yup I am having the same issue. Please advise.

**Comment by dasteralo** [comment]
Hello,
Same problem for me. Does anyone has a solution ?
Thanks

**Comment by dasteralo** [comment]
Hello,
Problem solved by reediting .htaccess file. It has something to do with url rewriting.
Hope this help

**Comment by selwynorren** [comment]
Would you mind sharing what you edited?

**Comment by dasteralo** [comment]
It was a problem with url rewrinting in my htaccess
`RewriteRule . - [E=REWRITEBASE:/]`
instead of 
`RewriteRule . - [E=REWRITEBASE:/old]`
In Prestashop you can edit a new htaccess file by disable/enable SEO friendly url option.

**Comment by smartdatasoft** [comment]
hello, Just enable the non seo url and the enable seo friendly url smartblog will add there own rules. then your featured image will show
