### ISSUE TITLE
Class error

### ISSUE THREAD

**Issue by Eolia** [smartdatasoft/smartblog#38]
Hi,
After install, if i want to edit a post, i have this error: 
PHP Fatal error:  Call to undefined method SmartBlogHelperTreeCategories::setDataSearch() in /var/www/clients/client1/web2/web/modules/smartblog/classes/SmartBlogHelperTreeCategories.php on line 311

This method not exists in the file...

**Comment by SLIVERPOOS** [comment]
I have the same problem:
Fatal error: Call to undefined method SmartBlogHelperTreeCategories::setDataSearch() in
... /modules/smartblog/classes/SmartBlogHelperTreeCategories.php on line 311

And I can't create new post or edit old post - (HTTP ERROR 500 after I push the button "Add new blog post")

Problem started, when I update module smartblog from v.2.0.1 to v2.1.4
My Prestashop versions with this problem (1.6.0.14 and 1.6.0.9)

When I go back to the version v.2.0.1 - the problem disappears

Also, when I install smartblog v2.1.4 - on last available version of Prestashop 1.6.1.7 on local server (Denwer) - There no this kind of problem and module work perfectly well

Maybe this is problems associated with the version of the Prestashop?

**Comment by Eolia** [comment]
I have commented the line^^

**Comment by smartdatasoft** [comment]
Hello, Eolia which version of Prestashop you are using. I think there are some function missing for tree in your old Presashop

**Comment by Eolia** [comment]
It was installed on a 1.6.0.9 version...

**Comment by SLIVERPOOS** [comment]
smartdatasoft, can you help?
Or this kind of problem I can fix only by updating prestashop to 1.6.1.7 ?
In this case, may be necessary specify this in “README”?
(That smartblog can’t work with old prestashop versions 1.6.0.9 and 1.6.0.14)

**Comment by smartdatasoft** [comment]
hello, sorry  didn't test that. I will try to investigate that. if possible you can pull a fix for that

**Comment by SLIVERPOOLS** [comment]
Please, any help?
In version v.2.0.1 very significant problem with comments (in backoffice not show in which post appeared comment)
but in version v2.1.4 — this problem is disappear.
We really need comments in blog but can't update module.
Please!
Thank you

**Comment by Xabico** [comment]
Hi !!!
I've found same problem with Smartblog 2.1.2 installed in Prestashop 1.6.1.9 and still don't have any solution for this. Long time to wait for developers solution, maybe is better to use a different blog module for Prestashop... 
What do you think?
Cheers
Xab

This is the error showed triying to edit a Post or Categories Blog and the files affected:

[PrestaShopException]

Data value must be an traversable array
at line 150 in file classes/tree/Tree.php

145.     }
146. 
147.     public function setDataSearch($value)
148.     {
149.         if (!is_array($value) && !$value instanceof Traversable) {
150.             throw new PrestaShopException('Data value must be an traversable array');
151.         }
152. 
153.         $this->_data_search = $value;
154.         return $this;
155.     }

TreeCore->setDataSearch - [line 311 - modules/smartblog/classes/SmartBlogHelperTreeCategories.php] - [1 Arguments]
SmartBlogHelperTreeCategories->getData - [line 320 - modules/smartblog/classes/SmartBlogHelperTreeCategories.php]
SmartBlogHelperTreeCategories->render - [line 546 - modules/smartblog/controllers/admin/AdminBlogPostController.php]
AdminBlogPostController->renderForm - [line 2039 - classes/controller/AdminController.php]
AdminControllerCore->initContent - [line 189 - classes/controller/Controller.php]
ControllerCore->run - [line 367 - classes/Dispatcher.php]
DispatcherCore->dispatch - [line 58 - admin/index.php]

**Comment by Orioldu** [comment]
I'm having the same error without fix for the moment

**Comment by smartdatasoft** [comment]
Please check new version released today and give feedback to us

**Comment by hdkcreative** [comment]
hi!  any solution ?
