### ISSUE TITLE
rewrite problem (?)

### ISSUE THREAD

**Issue by dmaglio** [smartdatasoft/smartblog#43]
i have installed smartblog from master (v. 2.1.4) but cannot enter into post. the smartblog page is visibile, but when i try to "read more" i see "post not found" error.
the url that i try is ```/blog/.html?slug=share-love-for-prestashop&module=smartblog```
(i try the example post before upload my site)

**Comment by smartdatasoft** [comment]
are you using latest version, did you update, last update. if this problem exits, please contact with our support support[at]smartdatasoft[dot]com, we will investigate that

**Comment by dmaglio** [comment]
yes, installed last version from master github

**Comment by smartdatasoft** [comment]
All this issue was solved. did you check yet. our new version is released today
