### ISSUE TITLE
Installation in prestashop version 1.6.7.x

### ISSUE THREAD

**Issue by wesleyrush** [smartdatasoft/smartblog#44]
Someone, who already managed to install the blog in prestashop version 1.6.7.X, could guide me on how to make it work?

**Comment by smartdatasoft** [comment]
Please download the package and then install. is there any issue for you.?

**Comment by wesleyrush** [comment]
After clicking to do the installation, the message appears that the module was not installed successfully. I click the "configure" button, it gives an error in the ADMINCONTROLLER class. After deleting the message I can access the settings of the smartblog, but does not appear the blog administration links (insert post, tags, categories). Is there any way to manually add these options to the prestashop admin panel?

**Comment by aalexandrakis** [comment]
In my case some sql creation statements has DEFAULT NULL in a key field, which is not allowed in MySql. Change the DEFAULT NULL to NOT NULL in the following create statements in prestashop/modules/smartblog/sql/install.php

- ps_smart_blog_category_lang > field id_lang 

- ps_smart_blog_category_shop > field id_shop 

- ps_smart_blog_comment_shop > field id_shop

- ps_smart_blog_post_lang >  field id_lang

- ps_smart_blog_post_category > field id_smart_blog_post

**Comment by Chitzi** [comment]
Thanks @aalexandrakis, it worked for me

**Comment by smartdatasoft** [comment]
@aalexandrakis  thank you for your help, we have marge this in our 1.6.x and also 1.7.x (development ) version will you please check all is ok  now https://github.com/smartdatasoft/smartblog/commit/f4f396879bc4a99b99a40079a6959d3062ac5b28
