### ISSUE TITLE
social sharing

### ISSUE THREAD

**Issue by totor321** [smartdatasoft/smartblog#45]
Hi
It seems that there's a problem with og tags 
Facebook doesn't find the right url for posts.
when people share, they only get meta_title and logo....

Thanks
Anne

**Comment by smartdatasoft** [comment]
our latest version have no problem of that, we will release that soon

**Comment by InterLaw-PL** [comment]
@smartdatasoft can you look: https://github.com/smartdatasoft/smartblog/issues/62

**Comment by smartdatasoft** [comment]
This issue already resolved in our new version
