### ISSUE TITLE
Prestashop 1.7 smartblog module ??

### ISSUE THREAD

**Issue by naturalman** [smartdatasoft/smartblog#46]
As we all know that **Prestashop 1.7 is available** , so we developers are waiting **free smartblog module** to be made available soon.. We will be grateful and also try to contribute to your project.. So please provide **latest smartblog for prestashop 1.7**... We are eagerly waiting for it... We hope that u will listen to our needs ans satisfy our needs as soon as possible.. And yes thanks a lot for Smartblog Module for Prestashop 1.6 version. You have done a great job man... Really awesome.. Go ahead.. And yes plz consider our needs... Again thanks a lot... :) @MuhammadArifurRahman @smartdatasoft ............

**Comment by smartdatasoft** [comment]
@naturalman our current version is almost ready for 1.7 it need some fine tune in post page. I was waiting for stable 1.7+ version. as rapid code change made problem

**Comment by naturalman** [comment]
Yaa sure and thanks a lot... Please provide us with the official link as soon as it is readily available.... @MuhammadArifurRahman @smartdatasoft

**Comment by naturalman** [comment]
Hey @MuhammadArifurRahman, **please provide **smartblog module for prestashop 1.7**. We being your clients are eagerly waiting for it. Please provide it asap. **Thank you****.

**Comment by smartdatasoft** [comment]
All our module will release in 1.7 once  it become stable. It is cost effective to change code easy version.

**Comment by naturalman** [comment]
Yaa sure ok **but please make it fast**. We will be grateful to you and your team. **@MuhammadArifurRahman** again thank you very much for quick response.

**Comment by Tomkinss** [comment]
Hi guys, any update on this?
I installed smartblog on my shop (version 1.7.0.4), but I got lot of errors.
![screen shot 2017-01-26 at 10 35 21](https://cloud.githubusercontent.com/assets/5066937/22326490/3388da4e-e3b3-11e6-8103-bc7c36a46737.png)

**Comment by mike14141** [comment]
@smartdatasoft Hello! Is it out yet for 1.7 ?

**Comment by ghost** [comment]
1.7 have been released since some times now, it's the downloaded version by default on prestashop website. Any update about smartblog 1.7 ready ?

**Comment by Inbloo** [comment]
Any update with prestashop 1.7?

**Comment by smartdatasoft** [comment]
Hello, Our 1.7 version is done, we are preparing to released

**Comment by Inbloo** [comment]
When are you planning to release it? I can help testing it. I'm upgrading to 1.7 one of my shops and the old one has your blog module

**Comment by smartdatasoft** [comment]
Hello, I just upload our new 1.7 version in git development branch and our old 1.6 version in 1.6.x . We are invited all to test and give feedback.

**Comment by smartdatasoft** [comment]
Our current development version work in 1.7.x
