### ISSUE TITLE
upgrade from 2.0.1 failed

### ISSUE THREAD

**Issue by 1ncom1ng** [smartdatasoft/smartblog#48]
good day!
i  am using 2.0.1 version for a long time. and somehow i cant use left column.
i thought that i can upgrade by replacing files directly, but error returned:
http500 when i try to edit posts or categories
error when i try to make new post - something about that parent category must be integer.

**Comment by araviel** [comment]
me too a lot of errors i just need the fix for sql injection, nothing more, thanks again

**Comment by rusbolik** [comment]
I also can not install the version downloaded here on 2.0.1.
How can I update it correctly?

**Comment by iamrobert** [comment]
You can upload the 2.0.2 update which can be downloaded from here:
http://nemops.com/overriding-modules-controllers-in-prestashop-1-6/#.WX9GyYiGOHs

Or his first post:
https://www.prestashop.com/forums/topic/545136-prestashop-blog-module/

However - 2.0.2 update to smartblog 2.1.3 doesn't work for me.

**Comment by rusbolik** [comment]
I was left with the same problem after the installation on the work, which came by mail-
Undefined index: content in .... \tools\smarty\sysplugins\smarty_internal_templatebase.php(157) : eval()'d code on line 93
and 
Trying to get property of non-object in .... \tools\smarty\sysplugins\smarty_internal_templatebase.php(157) : eval()'d code on line 93
and the same others in different lines

**Comment by smartdatasoft** [comment]
We have released new version , please check update
