### ISSUE TITLE
gsitemap not loading blog

### ISSUE THREAD

**Issue by selwynorren** [smartdatasoft/smartblog#49]
Hi,

I have noticed that when I generate a sitemap for the store I have 6 entries (equal to the six blog posts) but they are not referencing the url of the blog at all, they only show the root url. So teh sitemap module does see teh blog entries, it just does not reference them correctly.

Is there an updated fix for this?

Thanks

**Comment by Enumbin** [comment]
Thank you so much for pointing out the issue. Can you please open a support ticket on https://support.classydevs.com/support/ ?
Our team will look into the issue.
