### ISSUE TITLE
Blog Categories and sidebar

### ISSUE THREAD

**Issue by selwynorren** [smartdatasoft/smartblog#50]
Hi There,

I am sure I must be doing something wrong. I have completely removed the old smartblog system, ensured all configurations are removed, and all files were removed.

I then downloaded the module, installed and configured all the blog posts, adding a couple of extra ones as well. Everything seemed to work out just fine, until I started looking at the front end. Only the categories show in the sidepanel, none of the archive, or featured blog posts or anything else other than categories show.

The category counts are all wrong, its only showing the category count for the home category, as being 4 (original number of default post images). When looking at the database, the two additional blog posts added have no category settings in them at all. However in the back-office the categories are correctly set and showing as expected.

Finally when I view all blog entries, the moment a sixth blog entry is added while the limit is 5 per page, the pagination comes up (Correctly) however there seems to be an extra div tag, or sortieing as the sidepanel now shows bellow the pagination.

Please can you investigate, as I really love the ability to list products per blog entry as well as teh fixed rss feed. I really dont want to downgrade to the older version

you can view blog here:
https://orren.co.za/journal

Respectfully

**Comment by smartdatasoft** [comment]
Hello, Our new codebase release with optimized, can you check
