### ISSUE TITLE
TypeError: a is undefined in Related Product(s) AJAX request

### ISSUE THREAD

**Issue by ghost** [smartdatasoft/smartblog#54]
Hi!
Im getting error with the latest module.
`TypeError: a is undefined` in Related Product(s) AJAX request

http://imgurl.pl/img/bez-nazwy-1_5963e02295d22.jpg

**Comment by ghost** [comment]
Solved... My mistake!

**Comment by smartdatasoft** [comment]
We have move this to our new child module

**Comment by bhavikvaghani** [comment]
Hi,

Where can I get related product module?

Thanks. :)
