### ISSUE TITLE
Blind Sql Injection over id_post (comment form)

### ISSUE THREAD

**Issue by vsalrob** [smartdatasoft/smartblog#55]
The hidden input id_post in a comment form send, for example, value = 11. 
URL encoded POST input id_post was set to 11 AND 3*2*1=6 AND 381=381

The next values are performed:
1*1*1*11 => TRUE
11*381*376*0 => FALSE
21*5*2*999 => FALSE
11*1*1 => TRUE
1*1*1*1*1*11 => TRUE
21*1*1*0*1*1*381 => FALSE
11 AND 5*4=20 AND 381=381 => TRUE
11 AND 5*4=21 AND 381=381 => FALSE
11 AND 5*6<26 AND 381=381 => FALSE
11 AND 7*7>48 AND 381=381 => TRUE
11 AND 3*2*0=6 AND 381=381 => FALSE
11 AND 3*2*1=6 AND 381=381 => TRUE

I think that ti's important validate that id_post is a integer.

**Comment by smartdatasoft** [comment]
Hello, We have done all those. can you check our latest release?
