### ISSUE TITLE
Looking for a SearchController override to use PS top search to search blog contents

### ISSUE THREAD

**Issue by ghost** [smartdatasoft/smartblog#57]
Anybody?
Looking for a SearchController override to use Prestashop top search to search blog contents - desctiptions, tags, Any ideas? How much $$$ for that work?

**Comment by szpadlicho** [comment]
I,m up question ?

**Comment by smartdatasoft** [comment]
Hello, @PrestaShark can you share your idea. We have just uploaded our new version. You can test before officially released in forum

**Comment by Enumbin** [comment]
You can add awesome ajax search for products on your top header or anywhere else with Crazy Elements the best elementor based  drag & drop page builder for prestashop.
You can share your idea with us on https://support.classydevs.com/support/
Thank you
