### ISSUE TITLE
Module not found after upload

### ISSUE THREAD

**Issue by michaelgorter** [smartdatasoft/smartblog#59]
After I uploaded the zip file in my prestashop 1.6.1.17 installation, the module is not available (for install and activation) in the module list. This filters above the list are ok (installed & not installed / enabled & disabled).

Any ideas?

Thx, Michael.

**Comment by ekurguzov** [comment]
Have the same problem.

Could anybody assist with this issue?

Thanks.

**Comment by Buaha** [comment]
same problem :/

**Comment by smartdatasoft** [comment]
Hello, You need to upload the smartbog.zip not the main file. We have released our new update version please download and test
