### ISSUE TITLE
Login ADMIN use Blog , have a problem (about search filter)

### ISSUE THREAD

**Issue by Kvkuo** [smartdatasoft/smartblog#61]
Login ADMIN → Blog → There are 4 options → try to type keyword in search filter
my search filter only Blog Comments is work
but
Blog Category (Filter not work), 
Blog Post (Filter not work)

ext：
Blog Post  FILTER BY TITLE,  I type a keyword in Title, click search buttom, but, it did not work
It did not search to filter out my keywords

Is there anyone else who has the same problem with me and is there a way to fix it?
please help me,
thank you very much

![snap36](https://user-images.githubusercontent.com/34872705/34367104-52366750-eae1-11e7-94ec-91364d43de46.jpg)

**Comment by smartdatasoft** [comment]
@Kvkuo will you check our latest version , we have fix this issue http://prntscr.com/hyymjs
