### ISSUE TITLE
The new version 3.0.0 will work on 1.6.1.x?

### ISSUE THREAD

**Issue by rusbolik** [smartdatasoft/smartblog#63]
Through the standard installation of the module, I could not install and update

**Comment by rusbolik** [comment]
After uninstalling the old version, it turned out to install a new one. BUT!
1. When I try to click on the link "my_site / smartblog.html" I get the error 500
2. When I try to open a link to the back office in the back office, then I just have a white screen. It also happens with other items

Could you please tell me what I'm doing wrong?

sorry for my english. i used google translator

**Comment by smartdatasoft** [comment]
Hello, Yet it will work. Just use from the branch.

**Comment by TiaNex-Com** [comment]
NO,version 3.0.0   is not for ps 1.6.x

**Comment by smartdatasoft** [comment]
hello, version 2.x which you will find from 1.6.x branch will work 1.6.x
