### ISSUE TITLE
No image in frontend

### ISSUE THREAD

**Issue by PeterStudioWeb** [smartdatasoft/smartblog#74]
Hello!
Install last version from git (today 2018-01-22) and no image in post in frontend.
In admin images its okey. PS 1.7.2.4 (clean install).
Check a path of the image in frontend.
Thanks.

**Comment by smartdatasoft** [comment]
Will you please send your issue in our support with your site url , we will investigate that  https://smartdatasoft.zendesk.com

**Comment by fritaasd** [comment]
Same here

**Comment by smartdatasoft** [comment]
Please send your site access in the above support system our technical team will investigate the issue

**Comment by fritaasd** [comment]
detailingstore.pl/blog

2018-03-15 7:57 GMT+01:00 Muhammad Arifur Rahman <notifications@github.com>:

**Comment by smartdatasoft** [comment]
hello, did you upload image in your post.

**Comment by fritaasd** [comment]
Yes two images. One i article

W dniu wt., 20.03.2018 o 07:03 Muhammad Arifur Rahman <
notifications@github.com> napisał(a):

**Comment by PeterStudioWeb** [comment]
Sorry, very busy, I will write on following weeks

**Comment by fritaasd** [comment]
You dont know what is causing bug?

2018-03-20 21:53 GMT+01:00 PeterStudioWeb <notifications@github.com>:

**Comment by smartdatasoft** [comment]
We suggest to disable the seo mode and then enabled that, it will solve your issue.

**Comment by bhavikvaghani** [comment]
My site runs on nginx server.
Everything works fine only blog images are not displaying if rewrite mode is enable.

Any solution?

**Comment by duGuillaume** [comment]
> My site runs on nginx server.
Everything works fine only blog images are not displaying if rewrite mode is enable.
Any solution?

put this into your conf file (change '/blog/' by your config)

rewrite ^/blog/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /modules/smartblog/images/$1$2$3.jpg last;
rewrite ^/blog/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /modules/smartblog/images/$1$2.jpg last;

Here my conf

location / {
                # Redirect pretty urls to index.php
                try_files $uri $uri/ /index.php?$args;


                rewrite ^/blog/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /modules/smartblog/images/$1$2$3.jpg last;
                rewrite ^/blog/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /modules/smartblog/images/$1$2.jpg last;

                # Images
                rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
                rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
                rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
                rewrite ^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
                rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;

                # AlphaImageLoader for IE and fancybox
                rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;

                # Web service API
                rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;

                # Installation sandbox
                rewrite ^(/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;
        }

**Comment by psyray** [comment]
@duGuillaume 
For those who search for NginX rules, beware to take the ones in the code part and not the first ones which are bad.
So the good ones is (with escaped forward slash)
```
rewrite ^\/blog\/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?\/.+.jpg$ /modules/smartblog/images/$1$2$3.jpg last;
rewrite ^\/blog\/([a-zA-Z_-]+)(-[0-9]+)?\/.+.jpg$ /modules/smartblog/images/$1$2.jpg last;
```
[regexr.com/4d37m](https://regexr.com/4d37m)

**Comment by nabot58** [comment]
> > My site runs on nginx server.
> > Everything works fine only blog images are not displaying if rewrite mode is enable.
> > Any solution?
> 
> put this into your conf file (change '/blog/' by your config)
> 
> rewrite ^/blog/([0-9]+)(-[.__a-zA-Z0-9-]_)(-[0-9]+)?/.+.jpg$ /modules/smartblog/images/$1$2$3.jpg last;
> rewrite ^/blog/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /modules/smartblog/images/$1$2.jpg last;
> 
> Here my conf
> 
> location / {
> # Redirect pretty urls to index.php
> try_files $uri $uri/ /index.php?$args;
> 
> ```
>             rewrite ^/blog/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /modules/smartblog/images/$1$2$3.jpg last;
>             rewrite ^/blog/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /modules/smartblog/images/$1$2.jpg last;
> 
>             # Images
>             rewrite ^/([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$1$2$3.jpg last;
>             rewrite ^/([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$1$2$3$4.jpg last;
>             rewrite ^/([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$1$2$3$4$5.jpg last;
>             rewrite ^/([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$1$2$3$4$5$6.jpg last;
>             rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$1$2$3$4$5$6$7.jpg last;
>             rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$1$2$3$4$5$6$7$8.jpg last;
>             rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$1$2$3$4$5$6$7$8$9.jpg last;
>             rewrite ^/([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])([0-9])(-[_a-zA-Z0-9-]*)?(-[0-9]+)?/.+.jpg$ /img/p/$1/$2/$3/$4/$5/$6/$7/$8/$1$2$3$4$5$6$7$8$9$10.jpg last;
>             rewrite ^/c/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+.jpg$ /img/c/$1$2$3.jpg last;
>             rewrite ^/c/([a-zA-Z_-]+)(-[0-9]+)?/.+.jpg$ /img/c/$1$2.jpg last;
> 
>             # AlphaImageLoader for IE and fancybox
>             rewrite ^images_ie/?([^/]+)\.(jpe?g|png|gif)$ js/jquery/plugins/fancybox/images/$1.$2 last;
> 
>             # Web service API
>             rewrite ^/api/?(.*)$ /webservice/dispatcher.php?url=$1 last;
> 
>             # Installation sandbox
>             rewrite ^(/install(?:-dev)?/sandbox)/(.*) /$1/test.php last;
>     }
> ```

Where i found the conf file in my prestashop? Thank you for answer

**Comment by jonnydhaka** [comment]
if face any issue then please contact with our support at https://support.classydevs.com/
