### ISSUE TITLE
it will show content of other language

### ISSUE THREAD

**Issue by TiaNex-Com** [smartdatasoft/smartblog#81]
it will show content of other language
about line 91,

modules/smartblog/controllers/front/details.php

change the code from

 $this->post = new SmartBlogPost($id_post, true, $this->context->language->id, $this->context->shop->id);

to

 $this->post = new SmartBlogPost($id_post, $this->context->language->id, $this->context->shop->id);

**Comment by Enumbin** [comment]
It already shows content of other languages. Thanks
