### ISSUE TITLE
HTTP instead of HTTPS in image of post

### ISSUE THREAD

**Issue by InterLaw-PL** [smartdatasoft/smartblog#82]
Why the photo added to the post with http, instead of https? This causes SSL errors. Do you have any ideas how fix this problem?

![img_1](https://user-images.githubusercontent.com/33103226/36944820-d8f32656-1fa3-11e8-9d5f-6dc79331bf17.jpg)

**Comment by rc-pl** [comment]
This issue is caused by unset useSSL variable in below statements

`$protocol_content = (isset($useSSL) and $useSSL and Configuration::get('PS_SSL_ENABLED')) ? 'https://' : 'http://';
`

quick fix is to change it to 

`$protocol_content = (Configuration::get('PS_SSL_ENABLED')) ? 'https://' : 'http://';
`

**Comment by InterLaw-PL** [comment]
@rc-pl - you're a magic! It works! :) 👍

**Comment by rc-pl** [comment]
pozdrawiam

**Comment by PusleckiPatryk** [comment]
I would like just to say, that if you want to fix this error all u have to do is to :
replace in /smartblog/classes/SmartBlogLink , line ~103:

`$return_val = $this->protocol_content . Tools::getMediaServer($uri_path) . $uri_path;`
to

`$protocol_content = ($this->ssl_enable) ? 'https://' : 'http://';
$return_val = $protocol_content . Tools::getMediaServer($uri_path) . $uri_path;`

**Comment by xavier7x** [comment]
@PusleckiPatryk sorry for my english

you are the best !!
April, 2020 and your solution works

**Comment by jonnydhaka** [comment]
hi,
Thanks a lot for fix this problem. we will add this our next version. 
If you have any problems in the future, you can contact our support.
https://support.classydevs.com/
Thank you
