### ISSUE TITLE
Display description (content) in post (posts.tpl)

### ISSUE THREAD

**Issue by InterLaw-PL** [smartdatasoft/smartblog#83]
I looked that in the posts.tpl on smrtblog > views > templates > front is missing a script displaying "description" with admin post page. This causes that "description" not to be displayed on the blog page.

Solution:

after: 
```
<div class="sdsarticle-des" style="text-align: left;">
                    {$post.short_description}
                   </div>
```
add:

```
<div class="sdsarticle-des" style="text-align: left;">
                    {$post.content}
                   </div>
```

**Comment by smartdatasoft** [comment]
hello, which version of smartbllog this issue occurs 1.6 or 1.7 we show description in details page.

**Comment by InterLaw-PL** [comment]
Smart Blog v2.2.0 - by SmartDataSoft, Presta Shop 1.6

**Comment by smartdatasoft** [comment]
hello, we have fix this in our last commit you can download the version from 1.6 branch,
