### ISSUE TITLE
Image load over HTTP instead of HTTPS

### ISSUE THREAD

**Issue by Szobi81** [smartdatasoft/smartblog#85]
Hello, 

I understand that this is a known issue, and the fix is:
"This issue is caused by unset useSSL variable in below statements

$protocol_content = (isset($useSSL) and $useSSL and Configuration::get('PS_SSL_ENABLED')) ? 'https://' : 'http://';

quick fix is to change it to

$protocol_content = (Configuration::get('PS_SSL_ENABLED')) ? 'https://' : 'http://';"

But please tell me where to change it? Already went through all the files in modules/smartblog/controllers/front 

Where else needs to be changed?

**Comment by templatin** [comment]
I fixed it by editing only those TPL files containing blog images. Replace the image source of blog images with below code.
Example: I used below code in this file: /modules/smartblog/views/templates/front/category_loop.tpl

`<img src="{$urls.base_url}modules/smartblog/images/{$post.id_post}-single-default.jpg">`

**Comment by wfpaisa** [comment]
I had the same problem:

/modules/smartblog/classes/SmartBlogLink.php

replace, line ~103:
```
$return_val = $this->protocol_content . Tools::getMediaServer($uri_path) . $uri_path;
```
to
```
$protocol_content = ($this->ssl_enable) ? 'https://' : 'http://';
$return_val = $protocol_content . Tools::getMediaServer($uri_path) . $uri_path;
```

**Comment by jonnydhaka** [comment]
hi,
Thanks a lot for fix this problem. we will add this our next version.
If you have any problems in the future, you can contact our support.
https://support.classydevs.com/
Thank you
