### ISSUE TITLE
Comments not working

### ISSUE THREAD

**Issue by premiero** [smartdatasoft/smartblog#86]
Recently, I added  smartblog v3.0.0 module to my Prestashop 1.7.2.2. I did notice, that i can't submit any comments to posts. Also i did notice that captcha numbers are always the same, they are not change after refresh or next/previous post. I have set "Auto accepted comment" and "Allow Guest Comment" to Yes, but still nothing. Any ideas?

**Comment by tomaspk** [comment]
I have the same problem.  Does anyone know how to remove it?

**Comment by sebix30** [comment]
Someone find any solution? I have this same problem. I have purchased vinova cariana theme with smart blog, and comments not working. When I press submit button,  nothing happens. I have prestashop 1.7.3.3
Please for help.

**Comment by JoseGutier** [comment]
Same issue >_<

**Comment by prestashopfrustrated** [comment]
Did anyone or does anyone know how to solve this Prestashop problem unable to make blog comments? Should we contact Prestashop anyone there in particular ?

**Comment by pantagru** [comment]
I have the same problem, comments not working. Have you found a solution?

**Comment by prestashopfrustrated** [comment]
Unfortunately not. We are using Prestashop and their only response is that we have to pay more money, even though we already did pay at the time of the original website which came with this "smartblog" with problems like so many other modules.

We don't know if Prestashop is a serious ecommerce software or what else is better? Do you have any experience with OScommerce ? We are considering using them or any other which doesn't have as many technical problems as does Prestashop.


________________________________

**Comment by pantagru** [comment]
I contacted also smartdatasoft module owner support by mail, but no answer at the moment.
I've changed and installed another free blog module that, except for some details, works well, including comment and capctha.
I've never used OScommerce. I've worked well with WordPress + WooCommerce plugin.

**Comment by prestashopfrustrated** [comment]
I've heard about wordpress + woo commerce, but we are with Prestashop. It has a lot of problems with almost every module it seems.

Are you saying you are working with WordPress + Woocommerce? Do you think your new free blog module will work with Prestashop? If yes, can you tell me what's the name of it? Thank you.
________________________________

**Comment by pantagru** [comment]
The new free blog module is for Preshashop and works well: http://www.prestabrain.com/product/prestashop-blog-platform/

**Comment by Enumbin** [comment]
We can see that the issue is fixed.
Open support ticket on https://support.classydevs.com/support/

**Comment by daftarmacauslot88** [comment]
[Link Slot Deposit Pulsa 5000 Tanpa Potongan MACAUSLOT88,](https://github.com/smartdatasoft/smartblog/issues/Link%20Slot%20Deposit%20Pulsa%205000%20Tanpa%20Potongan) [Daftar Situs Slot Deposit Pulsa 5000 2022 MACAUSLOT88,](http://slotpulsa5000.rf.gd/) [slot deposit pulsa 5000 tanpa potongan,](http://apcav.org/foro/profile/link-slot-deposit-pulsa-5000-tanpa-potongan/) [agen slot pulsa 5000,](https://videodataanalysis.com/community/profile/daftar-situs-slot-deposit-pulsa-5000-2022/) [situs slot deposit pulsa 5000,](https://rosydawnwiki.uden.ai/NJOLounge/profile/link-slot-deposit-pulsa-5000/) [situs slot pulsa 5000,](https://calgarydongbeiren.org/community/profile/daftar-situs-slot-deposit-pulsa-5000-2022/) [slot deposit pulsa 5000,](https://tradevn.net/congdong/profile/link-slot-deposit-pulsa-5000/) [situs slot deposit pulsa 5000 terpercaya,](https://abvisualdesign.com/index.php/community/profile/daftar-situs-slot-deposit-pulsa-5000/) [slot deposit pulsa 5000 tanpa potongan 2022](https://www.vanxuan.center/forums/profile/daftar-situs-slot-deposit-pulsa-5000), [Link Slot Deposit Pulsa 5000 Tanpa Potongan 2022,](https://forum.sapb1.vn/community/profile/link-slot-deposit-pulsa-5000/) [Slot Deposit Pulsa 5000 Tanpa Potongan 2022,](https://egverse.org/forums/profile/daftar-situs-slot-deposit-pulsa-5000/) [slot online gacor deposit pulsa 5000,](https://forum-foxess.pro/community/profile/daftar-situs-slot-deposit-pulsa-2022/) [agen slot 4d deposit pulsa 5000,](https://success-int.education/blog/index.php?entryid=2636) [agen gacor slot pulsa 5000](https://acem.co/blog/index.php?entryid=214), [agen slot 2022 gacor slot pulsa,](https://www.gjmrosa.org/forum/general-discussions/link-slot-deposit-pulsa-5000-tanpa-potongan-macauslot88) [slot pulsa gacor 5000,](https://school.stemacademy.sg/blog/index.php?entryid=3129) [mpo slot deposit pulsa 5000 tanpa potongan,](https://campus.metroquimica.net/blog/index.php?entryid=708) [slot deposit pulsa 5000,](https://90miles.ca/forum/profile/link-slot-deposit-pulsa-5000-tanpa-potongan/) [judi slot deposit pulsa 5000 tanpa potongan,](https://wp-cocoon.com/community/profile/daftar-situs-slot-deposit-pulsa-5000-2022/) [slot deposit pulsa 5000 tanpa potongan 2020](http://www.aplar.org/community/profile/link-slot-deposit-pulsa-5000-tanpa-potongan/) 




https://daftarmacauslot88.wixsite.com/slot-pulsa-5000
http://slotpulsa5000.rf.gd/
http://apcav.org/foro/profile/link-slot-deposit-pulsa-5000-tanpa-potongan/
https://videodataanalysis.com/community/profile/daftar-situs-slot-deposit-pulsa-5000-2022/
https://rosydawnwiki.uden.ai/NJOLounge/profile/link-slot-deposit-pulsa-5000/
https://calgarydongbeiren.org/community/profile/daftar-situs-slot-deposit-pulsa-5000-2022/
https://tradevn.net/congdong/profile/link-slot-deposit-pulsa-5000/
https://abvisualdesign.com/index.php/community/profile/daftar-situs-slot-deposit-pulsa-5000/
https://pecsi.vn/cong-dong/members/
https://www.vanxuan.center/forums/profile/daftar-situs-slot-deposit-pulsa-5000
https://forum.sapb1.vn/community/profile/link-slot-deposit-pulsa-5000/
https://egverse.org/forums/profile/daftar-situs-slot-deposit-pulsa-5000/
https://forum-foxess.pro/community/profile/daftar-situs-slot-deposit-pulsa-2022/
https://success-int.education/blog/index.php?entryid=2636
https://acem.co/blog/index.php?entryid=214
https://www.gjmrosa.org/forum/general-discussions/link-slot-deposit-pulsa-5000-tanpa-potongan-macauslot88
https://school.stemacademy.sg/blog/index.php?entryid=3129
http://www.aplar.org/community/profile/link-slot-deposit-pulsa-5000-tanpa-potongan/
https://wp-cocoon.com/community/profile/daftar-situs-slot-deposit-pulsa-5000-2022/
https://90miles.ca/forum/profile/link-slot-deposit-pulsa-5000-tanpa-potongan/
https://campus.metroquimica.net/blog/index.php?entryid=708

**Comment by samcangoreng** [comment]
<a class="waffle-rich-text-link" href="https://www.narakreatif.co.id/profile/cmd398/profile">https://www.narakreatif.co.id/profile/cmd398/profile</a>
<a class="waffle-rich-text-link" href="https://www.finku.id/profile/cmd398/profile">https://www.finku.id/profile/cmd398/profile</a>
<a class="waffle-rich-text-link" href="https://www.profesikeuanganexpo.id/profile/cmd398/profile">https://www.profesikeuanganexpo.id/profile/cmd398/profile</a>
<a class="waffle-rich-text-link" href="https://www.mahindra.id/profile/cmd398/profile">https://www.mahindra.id/profile/cmd398/profile</a>
<a class="waffle-rich-text-link" href="https://www.miels.id/profile/cmd398/profile">https://www.miels.id/profile/cmd398/profile</a>
<a class="waffle-rich-text-link" href="https://www.investingmom.id/profile/cmd398/profile">https://www.investingmom.id/profile/cmd398/profile</a>
<a class="waffle-rich-text-link" href="https://www.topspicks.tops.co.th/profile/cmd398/profile">https://www.topspicks.tops.co.th/profile/cmd398/profile</a>
<a class="waffle-rich-text-link" href="https://www.ateliermode.co.id/profile/cmd398/profile">https://www.ateliermode.co.id/profile/cmd398/profile</a>
<a class="waffle-rich-text-link" href="https://www.soulinabox.co.id/profile/cmd398/profile">https://www.soulinabox.co.id/profile/cmd398/profile</a>
<a class="waffle-rich-text-link" href="https://www.tastecloud.id/profile/audyveronicaa/profile">https://www.tastecloud.id/profile/cmd398/profile</a>
<a class="waffle-rich-text-link" href="https://www.wuhub.id/profile/cmd398/profile">https://www.wuhub.id/profile/cmd398/profile</a>
<a class="waffle-rich-text-link" href="https://www.rudyhadisuwarno.id/profile/cmd398/profile">https://www.rudyhadisuwarno.id/profile/cmd398/profile</a>

**Comment by elsakristoff** [comment]
Great Work! Five Stars for them! They made it look so easy through their skills and experience! I would suggest it to every single person out there who is confronting the same issues!
<a href="https://ultimatetransport123.com/">Best car transport companies</a>
