### ISSUE TITLE
got 500 internal error when try to add/edit post ?

### ISSUE THREAD

**Issue by fred2088** [smartdatasoft/smartblog#91]
Dear sir,

got 500 internal error when try to add/edit post ?

what module do i missing, I have try to uninstall all smartlog and install again, but got 500 internall during installation. after that smartblog and all released module are installed, all seems work fine, but just got error when try to add/edit demo post....

Regards

**Comment by dilero80** [comment]
I get the same error 500. My log says this 
[2018-10-24 16:17:47] request.CRITICAL: Uncaught PHP Exception Symfony\Component\Debug\Exception\FatalErrorException: "Compile Error: Declaration of AdminBlogPostController::setMedia() must be compatible with AdminControllerCore::setMedia($isNewTheme = false)" at /home/alteravi/public_html/modules/smartblog/controllers/admin/AdminBlogPostController.php line 0 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalErrorException(code: 0): Compile Error: Declaration of AdminBlogPostController::setMedia() must be compatible with AdminControllerCore::setMedia($isNewTheme = false) at /home/alteravi/public_html/modules/smartblog/controllers/admin/AdminBlogPostController.php:0)"} []

please help me out

thanks

**Comment by Yacinetio** [comment]
hi; i got the same error anyone can help?

**Comment by yalopov** [comment]
https://forum.c4.cz/prestashop-1-7-4-1-chyba-500-s-modulem-smartblog-t14262.html

it seems related to some breaking changes included at php 7.x, try to use an older php version

**Comment by fred2088** [comment]
changed to use wordpress

**Comment by JirkaDeLucina** [comment]
It really looks like problem with PHP 7.2. But downgrade to lower version is not solution. Does anyone have any solution where to fix it into the code?

**Comment by yalopov** [comment]
> It really looks like problem with PHP 7.2. But downgrade to lower version is not solution. Does anyone have any solution where to fix it into the code?

You can directly edit this file at line 119 https://github.com/smartdatasoft/smartblog/blob/5204e806b6357bfe3ae43223ad240cc001a6e36d/controllers/admin/AdminBlogPostController.php#L119
to `public function setMedia($isNewTheme = false) { ` and it will no longer throw that 500 error but i wouldn't not recommend it because the plugin will still throw errors silently

**Comment by brillianttheme** [comment]
I did as above, everything seems to be working, there are no errors. I edited an existing post and added a new one, everything is fine. Nyadesune, Thank you.

**Comment by AmAtuMundo** [comment]
> > Realmente parece un problema con PHP 7.2. Pero bajar a una versión más baja no es una solución. ¿Alguien tiene alguna solución donde fijarlo en el código?
> 
> Puede editar directamente este archivo en la línea 119
> 
> [smartblog / controllers / admin / AdminBlogPostController.php](https://github.com/smartdatasoft/smartblog/blob/5204e806b6357bfe3ae43223ad240cc001a6e36d/controllers/admin/AdminBlogPostController.php#L119)
> 
> Línea 119 en [5204e80](/smartdatasoft/smartblog/commit/5204e806b6357bfe3ae43223ad240cc001a6e36d)
> 
>       función  pública setMedia () { 
> 
> a `public function setMedia($isNewTheme = false) { `y ya no va a tirar ese error 500 pero no no lo recomendaría porque el plugin todavía arrojará errores en silencio

Hola!! que significa que puede arrojar errores e silencio? gracias

Edito: solucione el problema!! gracias Nyadesune. lo que me preocupa es estar dejando que algo se enquiste si no soluciono la raíz del problema.

**Comment by Enumbin** [comment]
We have solved the issue in 4.0

**Comment by alfasino9** [comment]
> We have solved the issue in 4.0

How we can download the 4.0 version? I only see the 3.0.

Best regards!
