### ISSUE TITLE
Problem with URL Rewrite for link posts and images

### ISSUE THREAD

**Issue by luisway2net** [smartdatasoft/smartblog#94]
Smartblog v3.0 and prestashop v1.7.3
Force Compilation activated
With Friendly url activated
![captura de pantalla 2018-06-18 a la s 11 27 27](https://user-images.githubusercontent.com/2183028/41542129-9d6ff33a-72ea-11e8-8cc4-60a5c6a7f0bb.png)

With Friendly url deactivated
![captura de pantalla 2018-06-18 a la s 11 29 52](https://user-images.githubusercontent.com/2183028/41542287-f499041c-72ea-11e8-9221-3c95767103e2.png)

What is the solution??

**Comment by Mlody87** [comment]
I have this same problem. Can't display images on front. On backend images are displayed.
Enabled ssl and friendly url.

**Comment by jmvaras** [comment]
The same for me. I can see images in Backend, but not in frontend. I use Prestashop 1.7.4.2 and Smart Blog 3.0.0. Friendly URL activated and SSL disabled. I've tried to disable friendly url, but then I can't access the blog from the frontend. I think it's a problem with RewriteRule in htaccess, but I can't make it run. It puts "No image available" at frontend, but image ok at backend. Thanks.

**Comment by jmvaras** [comment]
I've noticed than when I use the IP of the Prestashop web instead of the name of the domain, it works perfectly. The link in this case is: xxx.xxx.xxx.xxx/blog/2-single-default/xxx.jpg.
When I use the domain name in SEO and URLs, the link change to: www.xxx.com/blog/no-single-default/xxx.jpg, and does not work.

**Comment by jmvaras** [comment]
I've finally found that when I use the domain name in SEO and URL with www., it does not work, but it works with the domain without www. I don't know why.

**Comment by MaritzaTrujillo** [comment]
I have the same problem.

**Comment by MaritzaTrujillo** [comment]
My solution was to make a copy of my posts and to restart the smartblog module.

**Comment by Mlody87** [comment]
Thank YouTube for your help :)

pt., 8.03.2019, 05:30 użytkownik MaritzaTrujillo <notifications@github.com>
napisał:

**Comment by tobiasz77** [comment]
No luck here. Tried everything, including restarting the blog, recompiling, etc. Still getting "no-single-default" on frontend. Any solutions?

**Comment by sirius82** [comment]
Hello, did you find how to do ? Same problem. Even after module reinitialisation. The path to image content no-home-default. If I change by 3-home-default (if the post has ID3) it's ok. I don't understand why the path change if SSL activated. And if I unable SSL after, the path stays the same. I have to reinitialize the module.

**Comment by sirius82** [comment]
Finally, after module restart, unabled and enabled SEO, import of backuped tables and images, images are displayed ! (PS 1.7.5.2). Still the mixed content problem...

**Comment by rm-info** [comment]
Hi,

for me what worked is: 
- open `/modules/smartblog/htupdate.php`
- copy the content of `$htupdate` var
- paste it somewhere in `/.htaccess` next to other `RewriteRules`
- reload the page and voilà!

**Comment by Enumbin** [comment]
just refreshing the .htaccess by enabling and disabling https://prnt.sc/y0aivl this will do the job.
For further support please open support ticket at https://support.classydevs.com/support/

**Comment by tuxfamily** [comment]
**Hi**.

I'm late to the party, but after installing a fairly recent theme, I encountered this situation and a Google search led me here.
Upon examining the URLs in the HTML, I suspected some URL rewrite rules might be at play, but I wasn't sure where to find them.

**A big thanks** to @rm-info for pointing them out. 

But since I'm using Nginx, I've adapted them accordingly.

**So, for the next person** who stumbles upon this issue, here are the original Apache rules:

```apache
RewriteRule ^blog/([0-9]+)(\-[\.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}modules/smartblog/images/$1$2$3.jpg [L]
RewriteRule ^blog/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ %{ENV:REWRITEBASE}modules/smartblog/images/$1$2.jpg [L]
```

**And here are the Nginx rules**:

```nginx
location ~ ^/blog/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ {
    rewrite ^/blog/([0-9]+)(-[.*_a-zA-Z0-9-]*)(-[0-9]+)?/.+\.jpg$ /modules/smartblog/images/$1$2$3.jpg last;
}

location ~ ^/blog/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ {
    rewrite ^/blog/([a-zA-Z_-]+)(-[0-9]+)?/.+\.jpg$ /modules/smartblog/images/$1$2.jpg last;
}
```
