### ISSUE TITLE
"blog search" block title not translatable

### ISSUE THREAD

**Issue by cd2500** [smartdatasoft/smartblog#95]
Be aware that the title of the "Blog Search" is not translatable and also not the "search" in the searching field there.
PS 1.6.1.18 with php 5.6.30. 
Smart Blog 2.2.0,
Smart Blog Search 2.0.1
Smart Blog Archiv 2.0.4
Smart Blog Feed 2
Smart Blog Home Latest News 2.0
Smart Blog Latest Comments 2.0.1
Smart Blog AddThisButton 2.0.3
Smart Blog Popular Posts 2.0.1
Smart Blog Recent Posts 2.0.1
Smart Blog Tag 2.0.1

Strangely I can find on code of the module GetSmartBlogLink('smartblog_link'), 
when on all other blocks it is defined as: GetSmartBlogLink('smartblog'). 

When I change this  on smartblogsearcht.tpl accordingly to other tpl with working translation it will take no effect, so seems that there is someone else a bug on the code of the smartblogsearch widget.

![search](https://user-images.githubusercontent.com/3574112/42083294-c048cffa-7b8a-11e8-82e7-0e53dc69c038.png)

**Comment by Enumbin** [comment]
Done in version 2.0.2 of smart blog search module. For further issue please open support ticket on https://support.classydevs.com/support/
