### ISSUE TITLE
Summary page of all posts is showing English Blog Post Title

### ISSUE THREAD

**Issue by cd2500** [smartdatasoft/smartblog#97]
Found another bug: 
On summary page of "All new posts" the title of the posts are showing all in English instead of German for German shop site.
Site is English and German, both languages are added translations. PS 1.6.1.18, php version 5.6.30.
Smart Blog 2.2.0,
Smart Blog Search 2.0.1
Smart Blog Archiv 2.0.4
Smart Blog Feed 2
Smart Blog Home Latest News 2.0
Smart Blog Latest Comments 2.0.1
Smart Blog AddThisButton 2.0.3
Smart Blog Popular Posts 2.0.1
Smart Blog Recent Posts 2.0.1
Smart Blog Tag 2.0.1

![title](https://user-images.githubusercontent.com/3574112/42083080-23a86f20-7b8a-11e8-837b-811d9b571555.png)

**Comment by Enumbin** [comment]
We have fixed the issue in version 4.0.0  For further support please open ticket at https://support.classydevs.com/support/
